name: ArmorStandGUI
version: 1.0.0
main: me.maksyash.asgui.ArmorStandGUI
api-version: '1.16'
author: maskittt
description: Menu for creating and customizing an armorstand. My first plugin ever!
commands:
  as:
    description: Opens the menu for creating and customizing an armorstand.
    usage: /<command>
    aliases:
      - armorstand
permissions:
  asgui.command:
    description: Allows someone to run the /as or /armorstand command
    default: true